package action.actionLogic;

public enum MessageAction {
    BEFORE_SWITCH, AFTER_SWITCH, ROUND_END, TERRAIN_STOPPED, TERRAIN_STARTED, WEATHER_STARTED, WEATHER_STOPPED,
    BEFORE_ATTACK, AFTER_ATTACK, AFTER_DAMAGE, CHANGE_HP;
}
